apiVersion: v1
kind: Service
metadata:
  name: velero-ui-service
  namespace: velero
spec:
  selector:
    app.kubernetes.io/name: velero # Αυτό συνδέει το service με το pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP