apiVersion: v1
kind: ServiceAccount
metadata:
  name: junior-dev-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
spec:
  rules:
  - apiGroups: [""] # "" υποδηλώνει το core API group
    resources: ["pods", "pods/log", "services"]
    verbs: ["get", "watch", "list"] # Μόνο διάβασμα, ΟΧΙ delete, ΟΧΙ create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: junior-dev-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io