apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chrisignat/Platform-Engineer.git # <-- Βάλε το link από το δικό σου repo!
    targetRevision: main # <-- Βεβαιώσου ότι είναι το σωστό branch (main ή master)
    path: . # <-- Βάζουμε τελεία (.) επειδή το nginx.yaml είναι χύμα στον κεντρικό φάκελο
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true