apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 57.1.0
    helm:
      values: |
        alertmanager:
          enabled: false
        
        prometheusOperator:
          admissionWebhooks:
            enabled: false
          tls:
            enabled: false

        prometheus:
          prometheusSpec:
            retention: 1h
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi

        grafana:
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          # Εδώ ορίζουμε ρητά και τις δύο πηγές
          additionalDataSources:
            - name: Prometheus
              type: prometheus
              url: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              url: http://loki-stack.monitoring.svc:3100
              access: proxy
              isDefault: false

        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true