apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack-aws
  namespace: argocd
spec:
  project: default
  source:
    chart: localstack
    repoURL: https://localstack.github.io/helm-charts
    targetRevision: 0.6.14
    helm:
      values: |
        image:
          # Χρησιμοποιούμε το ρητό repository και pullPolicy Always για να ξεκολλήσει
          repository: localstack/localstack
          tag: 3.0.0
          pullPolicy: Always
        
        extraEnvVars:
          - name: SERVICES
            # ΜΟΝΟ δωρεάν υπηρεσίες. Αν υπάρχει RDS εδώ, θα φας πάλι Exit 55.
            value: "s3,sqs,lambda,sns,dynamodb,iam,apigateway"
          - name: ACTIVATE_PRO
            value: "0"
          - name: DEBUG
            value: "1"
          - name: LAMBDA_EXECUTOR
            value: "local"
          - name: LOCALSTACK_AUTH_TOKEN
            value: ""
        
        # Απενεργοποιούμε το persistence προσωρινά για να σβηστούν παλιά Pro configs
        persistence:
          enabled: false

        mountDind:
          enabled: false

        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: localstack

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true