apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack-aws
  namespace: argocd
spec:
  project: default
  source:
    chart: localstack
    repoURL: https://localstack.github.io/helm-charts
    targetRevision: 0.6.14
    helm:
      values: |
        image:
          tag: latest
        
        # Ρυθμίσεις για τη Δωρεάν Έκδοση
        extraEnvVars:
          - name: SERVICES
            # Αφαιρέθηκε το RDS (είναι Pro). Προστέθηκαν οι βασικές δωρεάν υπηρεσίες.
            value: "s3,sqs,lambda,sns,dynamodb,iam,apigateway"
          - name: DEBUG
            value: "1"
          - name: LAMBDA_EXECUTOR
            value: "local"
        
        # Απενεργοποίηση Docker support για να μην ψάχνει το /var/run/docker.sock
        mountDind:
          enabled: false

        # Πόροι Συστήματος (Resources) - Η free έκδοση είναι πιο ελαφριά
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"

        # Persistence για να σώζονται τα δεδομένα σου
        persistence:
          enabled: true
          size: 5Gi
        
        service:
          type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: localstack

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true