apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  source:
    chart: cost-analyzer
    repoURL: https://kubecost.github.io/cost-analyzer/
    targetRevision: 2.2.0
    helm:
      values: |
        kubecostProductConfigs:
          clusterName: my-lab-cluster
          # Εδώ σιγουρεύουμε ότι κοιτάει τον Prometheus στο namespace monitoring
          prometheusExternalUrl: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          prometheusMgmtApiEndpoint: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
          
        # ΑΠΕΝΕΡΓΟΠΟΙΗΣΗ ΟΛΩΝ ΤΩΝ ΕΞΤΡΑ
        prometheus:
          enabled: false
          fqdn: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
        
        grafana:
          enabled: false  # Μην φτιάχνεις δεύτερο Grafana
        
        # Ενεργοποίηση του ServiceMonitor για να το βλέπει ο Operator σου
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: monitoring # Αυτό πρέπει να ταιριάζει με το όνομα του monitoring app σου
  destination:
    server: https://kubernetes.default.svc
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true